name: Build Emscripten

on:
  workflow_dispatch:
  push:
    branches:
    - emscripten-new

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: mymindstorm/setup-emsdk@v13

      - name: Prepare web data
        run: ./build-scripts/prepare-web-data.sh

      - name: Build with emcc (emscripten)
        run: ./build-scripts/build-emscripten.sh

      - name: Assemble web bundle
        run: |
          ./build-scripts/prepare-web.sh

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: play-cdda
          path: build/*
