name: Check pull request head branch name

on:
  pull_request:
    types:
      - opened

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    if: github.head_ref == 'master' && github.repository == 'CleverRaven/Cataclysm-DDA'
    steps:
			# https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: pr
          path: pr/
