name: Flake8 Python linting

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - name: run Flake8
      run: flake8
