name: Sort new contributors for test approval

on:
  pull_request:
    types:
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user has any merged PRs in this reposiory
        id: pr-check
        env:
          GITHUB_EVENT_PULL_REQUEST_USER_LOGIN: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          author="${GITHUB_EVENT_PULL_REQUEST_USER_LOGIN}"
          pr_count=$(gh pr list --state merged --author $author --json number | jq 'length')

          echo "Debug: $author with $pr_count merged PRs."
          echo "pr_count=$pr_count" >> $GITHUB_OUTPUT
      - name: Save PR number
        if: ${{ steps.pr-check.outputs.pr_count != 0 }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.number }} > ./pr/NR
      - name: Dummy PR number
        if: ${{ steps.pr-check.outputs.pr_count == 0 }}
        run: |
          mkdir -p ./pr
          echo > ./pr/NR
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: pr
          path: pr/
