name: Code Style Reviewer

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    paths:
      - '**.json'
      - '**.cpp'
      - '**.h'
      - '**.c'
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    paths:
      - '**.json'
      - '**.cpp'
      - '**.h'
      - '**.c'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  style-code:
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.draft == false }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        ref: '${{ github.event.pull_request.head.sha }}'
        persist-credentials: false

    - run: sudo apt-get install astyle

    - run: make astyle-fast
    - run: make style-all-json-parallel

    - name: Create pr comment artifacts
      if: ${{ failure() && github.event_name == 'pull_request' && steps.run_iwyu.outputs.has_errors != 0 }}
      working-directory: Cataclysm-DDA
      run: |
        set +e
        git diff --exit-code
        if [ $? -ne 0 ]; then
          mkdir -p ../suggestions
          git diff > ../suggestions/diff.txt
          echo ${{ github.event.pull_request.number }} > ../suggestions/pr_number
          echo ${{ github.event.pull_request.head.sha }} > ../suggestions/commit_sha
        fi
        exit 1
    - name: Upload pr comment artifacts
      if: ${{ failure() && github.event_name == 'pull_request' && steps.run_iwyu.outputs.has_errors != 0 }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: suggestions
        path: suggestions/

        # tool_name: '[JSON & C++ formatters](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/c++/DEVELOPER_TOOLING.md)'
